services:

  nextjs:
    container_name: t42-nextjs
    build: ./next-js
    # ports:
    #   - 3001:3000

  django:
    container_name: t42-django
    build: ./django
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - avatars:/app/media/
    # ports:
    #   - 8000:8000
      

  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379

  postgres:
    container_name: t42-postgres
    build: ./postgres
    # restart: on-failure
    # container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    
  nginx:
    container_name: t42-nginx
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nextjs
      - django
    volumes:
      - avatars:/app/media/

volumes:
  dbdata:
  avatars: